### ISSUE TITLE
Many "Refresh workspace" jobs

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/eclipseide-jdtls#37]
It looks like JDT-LS triggers lots of workspace refresh, hurting the overall performance and reactivity of the IDE.

**Comment by mickaelistria** [comment]
I see 1 system job stuck
```
"Worker-9: Initialize workspace" #68 [872338] prio=5 os_prio=0 cpu=3081.39ms elapsed=904.79s tid=0x00007f030803b160 nid=872338 waiting for monitor entry  [0x00007f035c6a4000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.eclipse.core.internal.jobs.JobManager.select(JobManager.java:1436)
	- waiting to lock <0x000000008387e988> (a java.lang.Object)
	at org.eclipse.core.internal.jobs.JobManager.select(JobManager.java:1427)
	at org.eclipse.core.internal.jobs.JobManager.find(JobManager.java:776)
	at org.eclipse.jdt.ls.core.internal.JobHelpers.getJob(JobHelpers.java:206)
	at org.eclipse.jdt.ls.core.internal.JobHelpers.waitForJobs(JobHelpers.java:187)
	at org.eclipse.jdt.ls.core.internal.JobHelpers.waitForBuildJobs(JobHelpers.java:169)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:295)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
This seems to lock the workspace for 1 hour, and many subsequent jobs are then stuck or failing.

**Comment by mickaelistria** [comment]
another full stack trace attached
[jstack.txt](https://github.com/redhat-developer/eclipseide-jdtls/files/11040948/jstack.txt)
I think the `waitForBuildJobs` which seems run in a workspace job (and thus possibly working the whole workspace) can be a major issue here in making the IDE unusable. I've submitted https://github.com/eclipse/eclipse.jdt.ls/pull/2552 which could hopefully improve that (by making the wait not block workspace)

**Comment by mickaelistria** [comment]
I'm not seeing those any longer.
