### ISSUE TITLE
Unusable (freeze, huge resource consumption...) with latest JDT-LS build

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/eclipseide-jdtls#81]
Let's make sure issue is not already fixed in snapshots first.

- [x] I verified I can reproduce this issue against latest [snapshots build](https://github.com/redhat-developer/eclipseide-jdtls#-installation)

## Steps to reproduce

From a fresh installation and clean workspace:

* get eclipseide-jdtls with JDT-LS 202306162235 or later

I tried

* Starting the IDE,
* Open a .java file

I expected: nothing bad

But got: Frozen IDE

## Here is some relevant log output form (`<workspace>/.metadata/.log`)

jstack shows hundreds of pending threads of the form
```
"Worker-35: JDT-LS (in process)" #103 [73349] prio=5 os_prio=0 cpu=1.37ms elapsed=22.98s tid=0x00007f776000e5b0 nid=73349 waiting for monitor entry  [0x00007f774e150000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:66)
	- waiting to lock <0x0000000084802270> (a java.lang.Object)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
	at jdk.proxy10.$Proxy29.notifyProgress(jdk.proxy10/Unknown Source)
	at org.eclipse.jdt.ls.core.internal.handlers.ProgressReporterManager$ProgressReporter.sendStatus(ProgressReporterManager.java:283)
	at org.eclipse.jdt.ls.core.internal.handlers.ProgressReporterManager$ProgressReporter.sendProgress(ProgressReporterManager.java:237)
	at org.eclipse.jdt.ls.core.internal.handlers.ProgressReporterManager$ProgressReporter.subTask(ProgressReporterManager.java:208)
	at org.eclipse.lsp4e.progress.LSPProgressManager.begin(LSPProgressManager.java:143)
	at org.eclipse.lsp4e.progress.LSPProgressManager.lambda$1(LSPProgressManager.java:106)
	at org.eclipse.lsp4e.progress.LSPProgressManager$$Lambda$1147/0x00000001009c71f0.run(Unknown Source)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The error happens since https://github.com/eclipse/eclipse.jdt.ls/commit/348252b6fa3d61d02145707d0f6d244c57ddf1fa , it looks like this change changes the execution path also in LSP4E to put it in a bad situation. One possibility is to review how LSP4E handles window/workDoneProgress/create .

@rgrunber pointed also to https://github.com/eclipse/eclipse.jdt.ls/blob/5a7e89f98063624443e85f807723f25969983292/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java#L242-L243 which gives the impression JDT-LS overrides the default progress monitor for Eclipse Platform. While this could make sense for a standalone application, it isn't a desired behavior in the "API-level" integration we're doing in eclipseide-jdtls. So one other potential solution to try is to move those lines in the application level, which doesn't affect eclipseide-jdtls.

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by mickaelistria** [comment]
I can confirm that commenting
```java
//		progressReporterManager = new ProgressReporterManager(client, preferenceManager);
//		Job.getJobManager().setProgressProvider(progressReporterManager);
```
in `JDTLanguageServer.connectClient()` seems to fix the issue.
The javadoc for `setProgressProvider` tells it clearly:
```
 * This method is intended for use by the currently executing Eclipse application.
 * Plug-ins outside the currently running application should not call this method.
```
So JDT-LS needs some adaptation here.

**Comment by akurtakov** [comment]
This issue no longer exists as it has been fixed via https://github.com/eclipse/eclipse.jdt.ls/commit/a762376aa63b3ca850552e396bfbe7bbe534170e
